# Generated by Django 4.0 on 2021-12-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_life', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EatBabe',
            new_name='EatBaby',
        ),
    ]
